server:
  port: 8089

spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
  mail:
    host: smtp.gmail.com
    port: 587
    username: tracpham2k5@gmail.com
    password: fpeeoawbkcrknyip
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
