server:
  port: 8081

spring:
  application:
    name: identity-service

  # --- CẤU HÌNH KẾT NỐI POSTGRESQL ---
  datasource:
    url: jdbc:postgresql://localhost:5432/st3plearn
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  # --- CẤU HÌNH HIBERNATE (TỰ TẠO BẢNG) ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # --- TẮT FLYWAY TRONG LÚC DEV ---
  flyway:
    enabled: false

# --- CẤU HÌNH KẾT NỐI TRẠM DANH BẠ ---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true