server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Bật tính năng tự tìm đường qua Eureka
          lower-case-service-id: true
      routes:
        # Luật định tuyến cho Identity Service
        - id: identity-service-route
          uri: lb://identity-service # lb = Load Balancer (Tự động cân bằng tải)
          predicates:
            - Path=/api/auth/**, /api/users/**, /api/admin/users/**

        # THÊM MỚI: Luật định tuyến cho Catalog Service
        - id: catalog-service-route
          uri: lb://catalog-service
          predicates:
            - Path=/api/catalog/**, /api/courses/**, /api/categories/**, /api/tags/**, /api/wishlists/**, /api/reports/**, /api/admin/reports/**, /api/admin/courses/**

        - id: learning-service-route
          uri: lb://learning-service
          predicates:
            - Path=/api/enrollments/**, /api/learning/**

        - id: payment-service-route
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**, /api/transactions/**

        - id: admin-service-route
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**

        - id: ai-service-route
          uri: http://127.0.0.1:7777
          predicates:
            - Path=/api/ai/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: VGhpc0lzQVN0cm9uZ0pXVFNlY3JldEtleUZvckhTMjU2MjAyNg==